auto create img/ directory when insert image
Rahi374/org-notebook pull request #2
Opened 2017-03-11 07:13 UTC by stardiviner

2017-03-11 20:57 UTC, Rahi374 commented
Thank you for the fix. However:

- If `./img/` doesn't exist, then the block of code right after `(interactive)` will fail as well, therefore please move this line there.
- `Symbol's function definition is void: f-directory-p`, therefore please use `file-directory-p`

2017-03-12 03:01 UTC, stardiviner commented
I updated my commit, and use `(unless (file-directory-p "./img") (make-directory "./img"))`.

2017-03-12 03:42 UTC, Rahi374 commented
You didn't fix either of the things I requested.
Additionally, please remove the `(unless ...)` expression.

2017-03-12 03:44 UTC, Rahi374 requested changes

2017-03-12 03:44 UTC, Rahi374 commented on org-notebook.el
> +    (or (f-directory-p "./img") (make-directory "./img"))
Change `f-directory-p` to `file-directory-p`

2017-03-12 03:44 UTC, Rahi374 commented on org-notebook.el
> +    (unless (file-directory-p "./img") (make-directory "./img"))
Remove this line.

2017-03-12 03:44 UTC, Rahi374 commented on org-notebook.el
> +    (or (f-directory-p "./img") (make-directory "./img"))
Also move this line to in between lines 140 and 141, otherwise this autocreate img directory is useless.

2017-03-12 04:02 UTC, stardiviner commented on org-notebook.el
> +    (unless (file-directory-p "./img") (make-directory "./img"))
Sorry about this, I forgot this. I will update commit.

2017-03-22 04:55 UTC, Rahi374 commented
Fixed in [https://github.com/Rahi374/org-notebook/commit/d90c4aeca2442161e6dd89de175561af85aace03](https://github.com/Rahi374/org-notebook/commit/d90c4aeca2442161e6dd89de175561af85aace03)

2017-03-22 04:55 UTC, closed without merging